# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0013_product_video_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='video_url',
        ),
    ]
